import type { ProjectIcon as ProjectIconSpec } from '@workerdeck/protocol'
import {
  Anchor,
  Atom,
  Beaker,
  Bike,
  Binary,
  Blocks,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Cable,
  Camera,
  Car,
  Cat,
  CircuitBoard,
  Cloud,
  Code,
  Coffee,
  Cog,
  Compass,
  Container,
  Cpu,
  CreditCard,
  Database,
  Diamond,
  Dog,
  Feather,
  Film,
  Flame,
  FlaskConical,
  Folder,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Hexagon,
  House,
  Image,
  Key,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  Lock,
  Mail,
  Map,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Network,
  Newspaper,
  Notebook,
  Orbit,
  Package,
  Palette,
  PenTool,
  Phone,
  PiggyBank,
  Plane,
  Plug,
  Puzzle,
  Radar,
  Radio,
  Receipt,
  Rocket,
  Ruler,
  Satellite,
  Scale,
  Scissors,
  Server,
  Shield,
  Ship,
  ShoppingCart,
  Signal,
  Smartphone,
  Sparkles,
  Sprout,
  Square,
  Star,
  Sun,
  Table,
  Tag,
  Target,
  Telescope,
  Terminal,
  TestTube,
  TreePine,
  Trophy,
  Truck,
  Umbrella,
  Users,
  Wallet,
  Wand,
  Waves,
  Webhook,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react'
import type { ComponentType } from 'react'
import { cn } from '../../lib/utils.ts'

/**
 * A curated glyph set — **never a namespace import over lucide**: `import * as`
 * defeats tree-shaking and costs the VS Code sidebar bundle 927 KB against
 * 77 KB for these. An unlisted-but-valid name draws {@link Folder}; grow the
 * set freely, each addition is ~400 bytes.
 */
const GLYPHS: Record<string, ComponentType<{ className?: string }>> = {
  anchor: Anchor,
  atom: Atom,
  beaker: Beaker,
  bike: Bike,
  binary: Binary,
  blocks: Blocks,
  bot: Bot,
  box: Box,
  brain: Brain,
  briefcase: Briefcase,
  brush: Brush,
  bug: Bug,
  'building-2': Building2,
  cable: Cable,
  camera: Camera,
  car: Car,
  cat: Cat,
  'circuit-board': CircuitBoard,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  cog: Cog,
  compass: Compass,
  container: Container,
  cpu: Cpu,
  'credit-card': CreditCard,
  database: Database,
  diamond: Diamond,
  dog: Dog,
  feather: Feather,
  film: Film,
  flame: Flame,
  'flask-conical': FlaskConical,
  folder: Folder,
  'gamepad-2': Gamepad2,
  gauge: Gauge,
  gem: Gem,
  ghost: Ghost,
  gift: Gift,
  'git-branch': GitBranch,
  globe: Globe,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  hexagon: Hexagon,
  house: House,
  image: Image,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  lock: Lock,
  mail: Mail,
  map: Map,
  'message-circle': MessageCircle,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  network: Network,
  newspaper: Newspaper,
  notebook: Notebook,
  orbit: Orbit,
  package: Package,
  palette: Palette,
  'pen-tool': PenTool,
  phone: Phone,
  'piggy-bank': PiggyBank,
  plane: Plane,
  plug: Plug,
  puzzle: Puzzle,
  radar: Radar,
  radio: Radio,
  receipt: Receipt,
  rocket: Rocket,
  ruler: Ruler,
  satellite: Satellite,
  scale: Scale,
  scissors: Scissors,
  server: Server,
  shield: Shield,
  ship: Ship,
  'shopping-cart': ShoppingCart,
  signal: Signal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sprout: Sprout,
  square: Square,
  star: Star,
  sun: Sun,
  table: Table,
  tag: Tag,
  target: Target,
  telescope: Telescope,
  terminal: Terminal,
  'test-tube': TestTube,
  'tree-pine': TreePine,
  trophy: Trophy,
  truck: Truck,
  umbrella: Umbrella,
  users: Users,
  wallet: Wallet,
  wand: Wand,
  waves: Waves,
  webhook: Webhook,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
}

/** A project's icon — the render side of protocol's `ProjectIcon`. An image
 * icon cannot take the row's colour (an `<img>`-embedded SVG is its own
 * document); a repo that wants that should declare a glyph. */
export function ProjectIcon({
  icon,
  src,
  name,
  className,
}: {
  icon: ProjectIconSpec | undefined
  /** Resolved bytes for the `image` arm — an object URL or a data URL. **The
   * caller fetches**, because who can differs per client: a VS Code webview
   * cannot reach the gateway and must be handed a data URL by its extension
   * host. Absent draws nothing. */
  src?: string
  /** The project's name, for the alt text. */
  name?: string
  className?: string
}) {
  if (!icon) {
    return null
  }
  if (icon.type === 'image') {
    if (!src) {
      return null
    }
    return (
      <img
        src={src}
        alt=""
        aria-hidden
        title={name}
        // `object-contain`: a declared icon is whatever aspect the repo checked in.
        className={cn('inline-block size-3 shrink-0 object-contain', className)}
      />
    )
  }
  const Glyph = GLYPHS[icon.name] ?? Folder
  return <Glyph className={cn('inline-block size-3 shrink-0', className)} />
}
