import type { ModelCatalog } from '../adapter.ts'

export const CLAUDE_CATALOG: ModelCatalog = {
  provenance: 'supportedModels() of @anthropic-ai/claude-agent-sdk 0.3.293 (Claude Code CLI), extracted 2026-10-08',
  models: [
    {
      value: 'fable',
      resolvedModel: 'claude-fable-5-1',
      displayName: 'Fable 5.1',
      description: 'For your toughest challenges',
      reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      primary: true,
    },
    {
      value: 'claude-fable-5',
      resolvedModel: 'claude-fable-5',
      displayName: 'Fable 5',
      description: 'Most capable for your hardest and longest-running tasks',
      reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    {
      value: 'opus',
      resolvedModel: 'claude-opus-5-5',
      displayName: 'Opus 5.5',
      description: 'For complex work and everyday tasks',
      reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      primary: true,
    },
    {
      value: 'claude-opus-5',
      resolvedModel: 'claude-opus-5',
      displayName: 'Opus 5',
      description: 'Best for everyday, complex tasks',
      reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    {
      value: 'claude-opus-4-8',
      resolvedModel: 'claude-opus-4-8',
      displayName: 'Opus 4.8',
      description: 'Best for everyday, complex tasks',
      reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    {
      value: 'claude-opus-4-7',
      resolvedModel: 'claude-opus-4-7',
      displayName: 'Opus 4.7',
      description: 'Best for everyday, complex tasks',
      reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    {
      value: 'claude-opus-4-6',
      resolvedModel: 'claude-opus-4-6',
      displayName: 'Opus 4.6',
      description: 'Best for everyday, complex tasks',
      reasoningEfforts: ['low', 'medium', 'high', 'max'],
    },
    {
      value: 'sonnet',
      resolvedModel: 'claude-sonnet-5-5',
      displayName: 'Sonnet 5.5',
      description: 'Most efficient for simpler tasks',
      reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      primary: true,
    },
    {
      value: 'claude-sonnet-5',
      resolvedModel: 'claude-sonnet-5',
      displayName: 'Sonnet 5',
      description: 'Efficient for routine tasks',
      reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    {
      value: 'claude-sonnet-4-6',
      resolvedModel: 'claude-sonnet-4-6',
      displayName: 'Sonnet 4.6',
      description: 'Efficient for routine tasks',
      reasoningEfforts: ['low', 'medium', 'high', 'max'],
    },
    {
      value: 'haiku',
      resolvedModel: 'claude-haiku-5-5',
      displayName: 'Haiku 5.5',
      description: 'Fastest for quick answers',
      reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      primary: true,
    },
    {
      value: 'claude-haiku-4-5-20251001',
      resolvedModel: 'claude-haiku-4-5-20251001',
      displayName: 'Haiku 4.5',
      description: 'Fastest for quick answers',
      reasoningEfforts: [],
    },
  ],
}
