export { initialReplayTarget, REPLAY_HOLD_MAX_MS, staleAttach, useClaudeSession } from './hooks/use-session.ts'
export type { ConnectionState, UseClaudeSessionOptions, UseClaudeSessionResult } from './hooks/use-session.ts'
export { clearTranscriptCache } from './lib/transcript-cache.ts'
export { clearProfileUsageCache } from './lib/profile-usage-cache.ts'
export { clearDrafts } from './lib/draft-store.ts'
export { attachmentKind, useAttachments } from './hooks/use-attachments.ts'
export type { AttachmentKind, StagedAttachment, UseAttachmentsOptions, UseAttachmentsResult } from './hooks/use-attachments.ts'
export { scanPromptTokens } from './lib/prompt-tokens.ts'
export type { PromptToken } from './lib/prompt-tokens.ts'
export { useHostFileRoots, useHostFileSearch, useHostFileTree } from './hooks/use-host-files.ts'
export type { UseHostFileRootsResult, UseHostFileSearchResult, UseHostFileTreeResult } from './hooks/use-host-files.ts'
export { ancestorsWithin, flattenHostTree } from './lib/host-tree.ts'
export type { HostDirState, HostTreeRow } from './lib/host-tree.ts'
export { useProjectIcons } from './hooks/use-project-icons.ts'
export type { ClientForHost } from './hooks/use-project-icons.ts'
export { useDraft } from './hooks/use-draft.ts'
export type { UseDraftResult } from './hooks/use-draft.ts'
export { useProfileUsage } from './hooks/use-profile-usage.ts'
export type { UseProfileUsageOptions, UseProfileUsageResult } from './hooks/use-profile-usage.ts'
export { useSessionInfo } from './hooks/use-session-info.ts'
export type { UseSessionInfoResult } from './hooks/use-session-info.ts'
export { useOpenFiles } from './hooks/use-open-files.ts'
export type { UseOpenFilesResult } from './hooks/use-open-files.ts'
export { currentText, initialOpenFilesState, isDirty, openFilesReducer } from './lib/open-files.ts'
export type { OpenFile, OpenFilesAction, OpenFilesState } from './lib/open-files.ts'
export { useToolCallHost } from './hooks/use-tool-host.ts'
export type { UseToolCallHostOptions } from './hooks/use-tool-host.ts'
export { createToolCallHost } from './lib/tool-host.ts'
export type { ClientToolHandler, ClientToolResult, ToolCallHostOptions, ToolHostExecution, ToolHostRunner } from './lib/tool-host.ts'
export { applyEvent, hydrateToolResult, initialTranscriptState, rateLimitWindows, seedFromSessionInfo } from './lib/transcript.ts'
export type { ProducedFileRef, ToolResultImageRef, TranscriptItem, TranscriptState } from './lib/transcript.ts'
export { recapLine, summarizeSince, type RecapInput, type RecapSummary } from './lib/recap.ts'
