export type LocalCommandResult = {
  command: string
  stdout: string
  stderr: string
  exitCode: number
}

const LOCAL_COMMAND_CAVEAT =
  '<local-command-caveat>Caveat: the messages below were generated by the user while running local commands. ' +
  'DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.' +
  '</local-command-caveat>'

// One `<local-command-stdout|stderr>` element and nothing else: the transcript reducer anchors its match on the whole trimmed text.
export function localCommandTranscript(result: LocalCommandResult): string {
  const tag = result.exitCode === 0 ? 'local-command-stdout' : 'local-command-stderr'
  const lines = [`$ ${result.command}`]
  const stdout = result.stdout.trimEnd()
  const stderr = result.stderr.trimEnd()
  if (stdout) {
    lines.push(stdout)
  }
  if (stderr) {
    lines.push(stderr)
  }
  if (result.exitCode !== 0) {
    lines.push(`[exit ${result.exitCode}]`)
  }
  return `<${tag}>${lines.join('\n')}</${tag}>`
}

export function localCommandContext(pending: readonly string[]): string | undefined {
  if (pending.length === 0) {
    return undefined
  }
  return [LOCAL_COMMAND_CAVEAT, ...pending].join('\n')
}

export function isSlashCommand(text: string): boolean {
  return /^\s*\/[A-Za-z]/.test(text)
}
